import { Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "./ui/context/products";
import { SessionProvider } from "./ui/context/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ProductProvider>
            {children}
          </ProductProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
