import Navbar from '../ui/navbar'
import Chat from '../ui/chat'

export const metadata = {
  title: "Phone Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <Navbar />
        {children}
        <Chat />
        </>
  );
}
